insert into public.interest_categories (slug, name, emoji)
values
  ('arts-culture', 'Arts & Culture', '🎨'),
  ('tech', 'Tech', '💻'),
  ('etudes', 'Études', '📚'),
  ('sport', 'Sport', '⚽'),
  ('voyage-lifestyle', 'Voyage & Lifestyle', '✈️'),
  ('divertissement', 'Divertissement', '🎮'),
  ('vie-sociale', 'Vie sociale', '🤝'),
  ('ambition', 'Ambition', '🔥'),
  ('nature', 'Nature', '🌿'),
  ('bien-etre', 'Bien-être', '🧘')
on conflict (slug) do nothing;

insert into public.interests (category_id, name, emoji)
select ic.id, v.name, v.emoji
from public.interest_categories ic
join (
  values
    ('arts-culture', 'Musique', '🎵'),
    ('arts-culture', 'Chant', '🎤'),
    ('arts-culture', 'Danse', '💃'),
    ('arts-culture', 'Cinéma', '🎬'),
    ('arts-culture', 'Séries', '📺'),
    ('arts-culture', 'Théâtre', '🎭'),
    ('arts-culture', 'Photographie', '📸'),
    ('arts-culture', 'Dessin', '✏️'),
    ('arts-culture', 'Peinture', '🖌️'),
    ('arts-culture', 'Écriture', '📝'),
    ('arts-culture', 'Poésie', '📖'),
    ('tech', 'Programmation', '👨‍💻'),
    ('tech', 'Flutter', '📱'),
    ('tech', 'Développement Web', '🌐'),
    ('tech', 'Intelligence artificielle', '🤖'),
    ('tech', 'Cybersécurité', '🔐'),
    ('tech', 'Design UI/UX', '🎨'),
    ('tech', 'Jeux vidéo', '🕹️'),
    ('tech', 'Robotique', '🦾'),
    ('etudes', 'Lecture', '📖'),
    ('etudes', 'Mathématiques', '➗'),
    ('etudes', 'Sciences', '🔬'),
    ('etudes', 'Économie', '📈'),
    ('etudes', 'Finance', '💰'),
    ('etudes', 'Marketing', '📣'),
    ('etudes', 'Entrepreneuriat', '🚀'),
    ('etudes', 'Langues étrangères', '🌍'),
    ('sport', 'Football', '⚽'),
    ('sport', 'Basketball', '🏀'),
    ('sport', 'Volleyball', '🏐'),
    ('sport', 'Tennis', '🎾'),
    ('sport', 'Natation', '🏊'),
    ('sport', 'Running', '🏃'),
    ('sport', 'Salle de sport', '🏋️'),
    ('sport', 'Arts martiaux', '🥋'),
    ('sport', 'Randonnée', '🥾'),
    ('sport', 'Cyclisme', '🚴'),
    ('voyage-lifestyle', 'Voyage', '✈️'),
    ('voyage-lifestyle', 'Road trips', '🚗'),
    ('voyage-lifestyle', 'Découverte de restaurants', '🍽️'),
    ('voyage-lifestyle', 'Café', '☕'),
    ('voyage-lifestyle', 'Cuisine', '🍳'),
    ('voyage-lifestyle', 'Pâtisserie', '🥐'),
    ('voyage-lifestyle', 'Mode', '👗'),
    ('voyage-lifestyle', 'Shopping', '🛍️'),
    ('voyage-lifestyle', 'Décoration', '🏡'),
    ('divertissement', 'Gaming', '🎮'),
    ('divertissement', 'Anime & Manga', '🌸'),
    ('divertissement', 'Échecs', '♟️'),
    ('divertissement', 'Jeux de société', '🎲'),
    ('divertissement', 'Quiz', '🧠'),
    ('divertissement', 'Streaming', '📡'),
    ('vie-sociale', 'Faire de nouvelles rencontres', '👋'),
    ('vie-sociale', 'Sorties entre amis', '🎉'),
    ('vie-sociale', 'Soirées', '🥳'),
    ('vie-sociale', 'Bénévolat', '❤️'),
    ('vie-sociale', 'Networking', '💼'),
    ('vie-sociale', 'Débats', '🗣️'),
    ('ambition', 'Startups', '💡'),
    ('ambition', 'Freelance', '🖥️'),
    ('ambition', 'Création de contenu', '📲'),
    ('ambition', 'Investissement', '📊'),
    ('ambition', 'Trading', '📉'),
    ('ambition', 'Développement personnel', '📈'),
    ('ambition', 'Productivité', '⏰'),
    ('nature', 'Jardinage', '🌱'),
    ('nature', 'Animaux', '🐶'),
    ('nature', 'Écologie', '♻️'),
    ('nature', 'Camping', '⛺'),
    ('nature', 'Pêche', '🎣'),
    ('bien-etre', 'Méditation', '🧘'),
    ('bien-etre', 'Yoga', '🧘‍♀️'),
    ('bien-etre', 'Spiritualité', '🕊️'),
    ('bien-etre', 'Nutrition', '🥗')
) as v(slug, name, emoji)
on ic.slug = v.slug
on conflict (category_id, name) do nothing;
